#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChSGfPxWda6oCo8sSwZPzQIT4UzEhm7rs2k0fSraFAt user@devops
runcmd:
  - 'sudo apt update'
  - 'sudo apt install -y ruby-full ruby-bundler build-essential git'
  - 'sudo apt install mongodb -y'
  - 'sudo systemctl start mongodb'
  - 'sudo systemctl enable mongodb'
  - 'git clone -b monolith https://github.com/express42/reddit.git'
  - 'bash -c "cd reddit && bundle install && puma -d"'
